### PR TITLE
fix: use `composedPath` instead of `target`, fixes #278

### LINKED ISSUE #278: Dropdown closes on option selection when used in shadow DOM
### Describe the bug

When using this library inside a shadow DOM (e.g. inside a web component), the behavior of the dropdown is different compared to when used in the "normal" DOM. When selecting an option, the dropdown disappears.

### Reproduction

Here I created two custom elements, one without shadow, one with shadow DOM. Note the difference when selecting a selection option.

https://stackblitz.com/edit/vitejs-vite-czjnxx?file=filter.js

### Expectation

Behavior of the dropdown should ideally be consistent and should work the same inside and outside the shadow DOM.

### Environment Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.61 GB / 15.38 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: 124.0.6367.201
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/multiple-select-vanilla/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/multiple-select-vanilla/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by silvester-pari**
This PR introduces `e.composedPath()[0]` as an alternative for `e.target` to make the library usable inside a shadow DOM. Background: Because of [Event `target` Retargeting](https://www.w3.org/TR/2016/WD-shadow-dom-20160531/#event-target-retargeting) using `event.target` returns the ancestor (e.g. custom element) instead of the clicked element, resulting in erroneous behavior like closing the dropdown on click (see https://github.com/ghiscoding/multiple-select-vanilla/issues/278).

All instances of `e.target' have been replaced. The built bundle was tested in the minimal reproduction example and provided the desired result (behavior of dropdown inside shadow DOM was the same as without shadow DOM).

Closes https://github.com/ghiscoding/multiple-select-vanilla/issues/278.

### CODE REVIEW

**Comment by ghiscoding** [comment]
@silvester-pari so just to be clear, should I assume correctly that in a non-shadow environment, then `e.composedPath()[0]` is equal to `e.target`?

File: packages/demo/src/main.ts [hunk 1]
```diff
@@ -154,7 +154,7 @@ class Main {
     this.removeAllActiveLinks();
 
     // change active link to new route
-    const targetElm = e.target as HTMLElement;
+    const targetElm = e.composedPath()[0] as HTMLElement;
```
Comment (ghiscoding) [inline packages/demo/src/main.ts:157]: this is for the actual demo application, this will never be inside a Shadow DOM, I don't think we need this change

Comment (silvester-pari) [reply packages/demo/src/main.ts]: You're right, reverted this change.

**Comment by silvester-pari** [comment]
@ghiscoding I think (not being an expert) that it equals to `event.target` for non-shadow and for closed shadow cases, the real benefit is in open shadow cases. By using it in all cases it could be considered a bit of "overkill", but it's the only fine-grained way to access the true list of `EventTargets` on which an event listener will be invoked. If I understand correctly, it should always return an array (see [MDN - "Return value"](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath)). See also [here](https://stackoverflow.com/a/30021867) a demo in non-shadow cases (like in your multiple-select-vanilla package, where it's also working for non-shadow cases). The only potential downside could be that `composedPath()` only returns a filled array during event dispatch: https://stackoverflow.com/a/74610934. Not sure how exactly `event.target` behaves in this case.

If you'd like to add an util function, something like
```js
function isInShadow(node) {
   return node.getRootNode() instanceof ShadowRoot;
}
```
could be used in order to determine if the element is currently used in a shadow root (see [SO answer here](https://stackoverflow.com/a/63225241)). In this case I'd ask you to add the function or to provide guidance on structurizing this.

**Comment by ghiscoding** [comment]
ok after doing some googling too, it seems to always be filled on modern browser (available since Jan. 2020), but maybe just to be on the safe side we could do something like this external function 

```ts
protected getEventTarget(e: Event & { target: HTMLElement }) {
  if (e.composedPath) {
    return e.composedPath()[0] as HTMLElement;
  }
  return e.target as HTMLElement;
}
```

and then call it everywhere you had composed path

```ts
protected infiniteScrollHandler(e: (MouseEvent & { target: HTMLElement }) | null, idx?: number, fullCount?: number) {
  const target = this.getEventTarget(e);
```

if we have problem in the future, then we only have 1 function to fix :)

**Comment by silvester-pari** [comment]
I did as you suggested, however, I had to add a `// @ts-expect-error`, since without it says:

```
This condition will always return true since this function is always defined. Did you mean to call it instead? ts(2774)
```

Seems like TS is assuming every browser to have this already...

Thanks for the link, interesting read indeed!

**Comment by ghiscoding** [comment]
side note, if you like the lib, it would be nice to upvote it since it helps to make it more visible. Thanks
